Add default value on parse_block_list articles variable
This was introduced at 9f2037e7b8973601e954bdd7e38a0f1cc7983c4c
but broke patterns report since it introduced a new argument with no default value
needed at [pattern search](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/9f2037e7b8973601e954bdd7e38a0f1cc7983c4c/classes/search/pattern/class-patterndata.php#L113).

Exception raised before this fix when visiting
`/wp-json/plugin_blocks/v3/plugin_blocks_report/`:

```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function
P4GBKS\Blocks\BlockList::parse_block_list(), 1 passed in
/var/www/html/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/search/pattern/class-patterndata.php
on line 113 and exactly 4 expected in
/var/www/html/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/blocks/class-blocklist.php:76
Stack trace: #0 /var/www/html/wp-content/plugins/planet4-plugin-gutenberg-blocks/classes/search/pattern/class-patterndata.php(113):
P4GBKS\Blocks\BlockList::parse_block_list()
```